export class Model {
  "BaseRate": null;
  "BatchId": null;
  "BodyId": null;
  "BodyNameEn": null;
  "BranchCode": null;
  "CoreAppCode":null;
  "CoreBodyId": null;
  "CoreMakeId": null;
  "CoreModelId": null;
  "CoreRefNo": null;
  "CreatedBy": null;
  "EffectiveDateStart":any;
  "EffectiveDateEnd":any;
  "InsuranceId": null;
  "MakeId": null;
  "MakeNameEn": null;
  "ModelId": null;
  "ModelIdOld": null;
  "ModelNameEn": null;
  "NetRate":null;
  "ObsoleteFlag": null;
  "OtherBodyId1": null;
  "OtherBodyId2": null;
  "OtherMakeId1": null;
  "OtherMakeId2": null;
  "OtherModelId1": null;
  "OtherModelId2": null;
  "PrimaCode": null;
  "RefNo": any;
  "RegulatoryCode": null;
  "Remarks": null;
  "RopBodyId": null;
  "Status": "Y";
  "TplRate": null;
  "UploadedBy": null;
  "VehCc": null;
  "VehClass": null;
  "VehClassEn": null;
  "VehFueltype": null;
  "VehManfCountry": null;
  "VehManfCountryEn": null;
  "VehManfRegion": null;
  "VehManfRegionEn": null;
  "VehWeight": null;
  "VehicleModelCode": null;
  "batchId": null;
"CodeDescLocal":null;
}
